<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="Avalonia.Svg.Skia"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" />
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="System.Drawing.Common"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\Images\logo.svg"/>
        <AvaloniaResource Include="Assets\Images\logo.svg"/>
        <None Remove="Assets\Fonts\Phosphor.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\Phosphor.ttf"/>
        <None Remove="Assets\Fonts\Phosphor-Fill.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\Phosphor-Fill.ttf"/>
        <None Remove="Assets\Images\icon.svg"/>
        <AvaloniaResource Include="Assets\Images\icon.svg"/>
        <None Remove="Assets\Images\background-settings.svg"/>
        <AvaloniaResource Include="Assets\Images\background-settings.svg"/>
        <None Remove="Assets\Images\background-actions.svg"/>
        <AvaloniaResource Include="Assets\Images\background-actions.svg"/>
        <None Remove="Assets\Fonts\NotoSansJP.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP.ttf"/>
        <None Remove="Assets\Images\icon.ico"/>
        <AvaloniaResource Include="Assets\Images\icon.ico"/>
        <None Remove="Assets\Images\home-context-delete.png" />
        <AvaloniaResource Include="Assets\Images\home-context-delete.png" />
        <None Remove="Assets\Images\home-context-drawing.png" />
        <AvaloniaResource Include="Assets\Images\home-context-drawing.png" />
        <None Remove="Assets\Images\home-context-drawinglink.png" />
        <AvaloniaResource Include="Assets\Images\home-context-drawinglink.png" />
        <None Remove="Assets\Images\home-context-fileref.png" />
        <AvaloniaResource Include="Assets\Images\home-context-fileref.png" />
        <None Remove="Assets\Images\home-context-folder.png" />
        <AvaloniaResource Include="Assets\Images\home-context-folder.png" />
        <None Remove="Assets\Images\home-context-openfile.png" />
        <AvaloniaResource Include="Assets\Images\home-context-openfile.png" />
        <None Remove="Assets\Images\home-context-preview.png" />
        <AvaloniaResource Include="Assets\Images\home-context-preview.png" />
        <None Remove="Assets\Images\home-context-print.png" />
        <AvaloniaResource Include="Assets\Images\home-context-print.png" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionsPageView.axaml.cs">
            <DependentUpon>ActionsPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\PrintSettingsView.axaml.cs">
            <DependentUpon>PrinterSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionCustomPropertiesView.axaml.cs">
            <DependentUpon>ActionsTabCustomPropertiesView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionFileInfoView.axaml.cs">
            <DependentUpon>ActionsTabFileInfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionSaveModelView.axaml.cs">
            <DependentUpon>ActionsTabSaveModelView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionSaveDrawingView.axaml.cs">
            <DependentUpon>ActionsTabSaveDrawingView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionImportFileView.axaml.cs">
            <DependentUpon>ActionsTabImportFileView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionDrawingTemplateView.axaml.cs">
            <DependentUpon>ActionsTabDrawingTemplateView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ActionMacrosView.axaml.cs">
            <DependentUpon>ActionsTabMacrosView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BatchProcess3.Core\BatchProcess3.Core.csproj" />
    </ItemGroup>

</Project>
