<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="Avalonia.Svg.Skia"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" />
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="System.Drawing.Common"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\Images\logo.svg"/>
        <AvaloniaResource Include="Assets\Images\logo.svg"/>
        <None Remove="Assets\Fonts\Phosphor.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\Phosphor.ttf"/>
        <None Remove="Assets\Fonts\Phosphor-Fill.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\Phosphor-Fill.ttf"/>
        <None Remove="Assets\Images\icon.svg"/>
        <AvaloniaResource Include="Assets\Images\icon.svg"/>
        <None Remove="Assets\Images\background-settings.svg"/>
        <AvaloniaResource Include="Assets\Images\background-settings.svg"/>
        <None Remove="Assets\Images\background-actions.svg"/>
        <AvaloniaResource Include="Assets\Images\background-actions.svg"/>
        <None Remove="Assets\Fonts\NotoSansJP.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP.ttf"/>
        <None Remove="Assets\Images\icon.ico"/>
        <AvaloniaResource Include="Assets\Images\icon.ico"/>
        <None Remove="Assets\Images\home-context-delete.png" />
        <AvaloniaResource Include="Assets\Images\home-context-delete.png" />
        <None Remove="Assets\Images\home-context-drawing.png" />
        <AvaloniaResource Include="Assets\Images\home-context-drawing.png" />
        <None Remove="Assets\Images\home-context-drawinglink.png" />
        <AvaloniaResource Include="Assets\Images\home-context-drawinglink.png" />
        <None Remove="Assets\Images\home-context-fileref.png" />
        <AvaloniaResource Include="Assets\Images\home-context-fileref.png" />
        <None Remove="Assets\Images\home-context-folder.png" />
        <AvaloniaResource Include="Assets\Images\home-context-folder.png" />
        <None Remove="Assets\Images\home-context-openfile.png" />
        <AvaloniaResource Include="Assets\Images\home-context-openfile.png" />
        <None Remove="Assets\Images\home-context-preview.png" />
        <AvaloniaResource Include="Assets\Images\home-context-preview.png" />
        <None Remove="Assets\Images\home-context-print.png" />
        <AvaloniaResource Include="Assets\Images\home-context-print.png" />
        <None Remove="Assets\Fonts\NotoSansJP-Black.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Black.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Bold.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Bold.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-ExtraBold.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-ExtraBold.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Extralight.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Extralight.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Light.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Light.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Medium.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Medium.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Regular.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Regular.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Semibold.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Semibold.ttf" />
        <None Remove="Assets\Fonts\NotoSansJP-Thin.ttf" />
        <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Thin.ttf" />
        <None Update="Assets\Images\icon.icns">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Info.plist">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\PrintSettingsView.axaml.cs">
            <DependentUpon>PrinterSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ActionsPageView.axaml.cs">
          <DependentUpon>ActionsPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\HistoryPageView.axaml.cs">
          <DependentUpon>HistoryPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\HomePageView.axaml.cs">
          <DependentUpon>HomePageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\MainView.axaml.cs">
          <DependentUpon>MainView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\MacrosPageView.axaml.cs">
          <DependentUpon>MacrosPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ProcessPageView.axaml.cs">
          <DependentUpon>ProcessPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ReporterPageView.axaml.cs">
          <DependentUpon>ReporterPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\SettingsPageView.axaml.cs">
          <DependentUpon>SettingsPageView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionCustomPropertiesView.axaml.cs">
          <DependentUpon>ActionCustomPropertiesView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionDrawingTemplateView.axaml.cs">
          <DependentUpon>ActionDrawingTemplateView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionFileInfoView.axaml.cs">
          <DependentUpon>ActionFileInfoView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionImportFileView.axaml.cs">
          <DependentUpon>ActionImportFileView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionMacrosView.axaml.cs">
          <DependentUpon>ActionMacrosView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionPrintView.axaml.cs">
          <DependentUpon>ActionPrintView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionSaveDrawingView.axaml.cs">
          <DependentUpon>ActionSaveDrawingView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionSaveModelView.axaml.cs">
          <DependentUpon>ActionSaveModelView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BatchProcess3.Core\BatchProcess3.Core.csproj" />
    </ItemGroup>

</Project>
