<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>PrototypeTheme</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="**/*.xaml" />
    </ItemGroup>

</Project>
