<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\bolt-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="NationalInstruments.Visa" Version="25.5.0.13" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.8.2" />
  </ItemGroup>
</Project>
